name: Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: Release
    types: requested

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry add flake8 pytest pyinstaller
        poetry install
    - name: Lint with flake8
      run: poetry run flake8 . --show-source --statistics
    - name: Test with pytest
      run: poetry run pytest
    - name: Package with pyinstaller
      run: poetry run pyinstaller --onefile main.spec
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.workflow }}
        path: 'dist/windows'
    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        delete_workflow_pattern: ${{ github.workflow }}
        retain_days: 0
        keep_minimum_runs: 0
